name: 'Hashnode Blog Manager'
description: 'Manage Hashnode blog posts using GitHub Actions'
inputs:
  blog_path:
    description: 'Path to the blogs directory'
    required: true
  hashnode_access_token:
    description: 'Hashnode access token to authenticate API requests'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout triggering repository
      uses: actions/checkout@v4
      with:
        path: 'triggering-repo'
        fetch-depth: 0
    
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        repository: Mukund-Tandon/Hashnode-Blog-Manger
        path: 'action-repo'
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests==2.31.0
      shell: bash

    - name: Process blog changes
      run: |
        ls -la
        cd triggering-repo
        ls -la
        changed_files=$(git diff-tree --no-commit-id --name-only -r origin/main | grep "^${{ inputs.blog_path }}")
        if [[ -z "$changed_files" ]]; then
          echo "No changed files found in the specified directory."
        else
          IFS=$'\n' 
          for folder in $(echo "$changed_files" | xargs -n1 dirname | sort -u); do
            echo "Processing files in folder: $folder"
            files_in_folder=$(echo "$changed_files" | grep "^$folder")
            echo "Files in folder: $files_in_folder"
            
            folder_structure="{"
            for file in $files_in_folder; do
              content=$(cat "$file")
              folder_structure+="\"$file\": \'''$content\''',"
            done
            folder_structure="${folder_structure%,}"  # Remove trailing comma
            folder_structure+="}"

            echo "Folder Structure: $folder_structure"
            
            # Pass folder_structure to your Python script
            echo "$folder_structure" | python ../action-repo/scripts/main.py
          done
        fi
      shell: bash
