name: 'Hashnode Blog Manager'
description: 'Manage Hashnode blog posts using GitHub Actions'
inputs:
  blog_path:
    description: 'Path to the blogs directory'
    required: true
  hashnode_access_token:
    description: 'Hashnode access token to authenticate API requests'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout triggering repository
      uses: actions/checkout@v4
      with:
        path: 'triggering-repo'
        fetch-depth: 0
    
    - name: Checkout action repository
      uses: actions/checkout@v4
      with:
        repository: Mukund-Tandon/Hashnode-Blog-Manager
        path: 'action-repo'
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests==2.31.0
      shell: bash

    - name: Process blog changes
      run: |
        ls -l
        changed_files=$(git diff-tree --no-commit-id --name-only -r origin/main | grep "^${{ inputs.blog_path }}")
        
        if [[ -z "$changed_files" ]]; then
          echo "No changed files found in the specified directory."
        else
          for file in $changed_files
          do
            echo "Contents of $file:"
            if cat "$file" | python ./action-repo/scripts/main.py; then
              echo "Successfully printed and processed $file using main.py."
            else
              echo "Failed to check the file using main.py."
            fi
          done
        fi
      shell: bash
