name: hashnode blog manager

on:
    push:
        branches:
            - main

jobs:
    do_stuff:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                sparse-checkout: 'blogs'
                fetch-depth: 0

            - name: echo changes in files
              run: |
                changed_files=$(git diff-tree --no-commit-id --name-only -r origin/main)
                echo "Changed files: $changed_files" 
